---
engines:
  duplication:
    enabled: true
    config:
      languages:
        - php
        - css
  eslint:
    enabled: true
    env:
      jquery: true
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      standard: "WordPress-Core"
ratings:
  paths:
    - "**.js"
    - "**.css"
    - "**.php"
exclude_paths:
  - node_modules/**/*
  - languages/**
  # - css/**
  # - js/**
